### ISSUE TITLE
Create A Contract Verifier

### ISSUE THREAD

**Issue by yehia67** [topos-protocol/explorer#26]
## Is your proposal related to a problem?
Verifying deployed smart contracts

## Describe the solution you'd like
We depend mainly on the subgraph. The simplest way I found is  integrating the existing verifier service from [blockscout](https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier)
I will edit the config file. And use the docker installation/deployment.

## Describe alternatives you've considered
There are no alternatives, but I am still in the research phase and open to new solutions.

**Comment by sebastiendan** [comment]
Hey @yehia67, sorry for the late reply.

We've been thinking actually about adding Blockscout's contract verifier to our Blockscout instances (Topos Subnet and Incal). Then, in a later time, we'll think about using these contract verifier instances in our own Topos Explorer 👍

**Comment by yehia67** [comment]
Sounds good! If you need any help please let me know😄
